version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3308:3306
    networks:
      - movie-networks
  movie:
    depends_on:
      - mysql_db
    build: .
    container_name: movie_be
    env_file:
      - .env
    ports:
      - 3005:3001
    networks:
      - movie-networks
networks:
  movie-networks: